services:
  panel:
    build: .
    container_name: amnezia-panel
    restart: always
    volumes:
      - ./data.json:/app/data.json
      - ./instance:/app/instance
      - ./logs:/app/logs
      - ./tunnels_state.json:/app/tunnels_state.json
    ports:
      # nginx на хосте проксирует на 127.0.0.1:5000
      - "127.0.0.1:5000:5000"
